spring.application.name=mscartelera
server.port=8081
# Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${COGNITO_ISSUER_URI}

ms-asientos.url=http://localhost:8082

# Limita las conexiones simultáneas para ahorrar recursos
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
